name: Build & Release Unicorn Installer

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.1.4

permissions:
  contents: write  # Needed to create releases and upload artifacts

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [20.x]
      fail-fast: false  # Keep other OS builds even if one fails

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # PAT with repo scope for private repos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ensures Electron Builder can access GH

      - name: Create GitHub Release and attach artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Unicorn Installer ${{ github.ref_name }}
          artifacts: "dist/**/*"
          generateReleaseNotes: false
          immutableCreate: false
          makeLatest: legacy
        env:
          token: ${{ secrets.GH_TOKEN }}  # Must be your PAT for private repo
