name: Build & Release Unicorn Installer

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v7.0.3

permissions:
  contents: write  # Required to create releases and upload artifacts

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [20.x]
      fail-fast: false  # Continue other builds even if one fails

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Zip macOS app so GitHub can upload it
      - name: Zip macOS .app bundle
        if: matrix.os == 'macos-latest'
        run: |
          cd dist/mac-arm64
          zip -r "Shine Unicorn Installer-mac.zip" "Shine Unicorn Installer.app"

      # Upload artifacts to GitHub Release
      - name: Create GitHub Release and attach artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Unicorn Installer ${{ github.ref_name }}
          artifacts: |
            # Windows
            dist/**/*.msi
            dist/**/*.exe
            # Linux
            dist/**/*.AppImage
            dist/**/*.deb
            # Mac
            dist/mac-arm64/*.zip
          generateReleaseNotes: false
          immutableCreate: false
          makeLatest: legacy
        env:
          token: ${{ secrets.GH_TOKEN }}
